[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "my-app/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Uncomment the redirect rule if you're deploying a Single Page Application (SPA)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
